### ISSUE TITLE
Upload coverage to codecov

### ISSUE THREAD

**Issue by Luthaf** [huonw/travis-cargo#27]
It would be nice to be able to output coverage on [codecov](http://codecov.io). For now, we can do 

```
language: rust
sudo: false
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
install:
    - pip install --user travis-cargo codecov
    - export PATH=$PATH:$HOME/.local/bin
script:
    - travis-cargo build
    - travis-cargo test
after_success:
    - travis-cargo coverage --no-sudo
    - codecov --file target/kcov/kcov-merged/cobertura.xml
```

But a `travis-cargo codecov` subcommand could be nice!
