### ISSUE TITLE
Verify path dependencies

### ISSUE THREAD

**Issue by flying-sheep** [huonw/travis-cargo#34]
Hi, I just noticed a versioning bug: alexcrichton/flate2-rs#32

I wondered if this project could support catching those, i.e.

1. parse Cargo.toml
2. for each path dependency:

	1. Check if the path is a valid crate
	2. parse its Cargo.toml
	3. Check if its version corresponds to the version of the parent’s dependency.

In our case, this would have caused the CI build to fail because `flate2-rs/Cargo.toml` contains:

```toml
[dependencies]
miniz-sys = { path = "miniz-sys", version = "0.1.6" }
```

whereas `flate2-rs/miniz-sys/Cargo.toml` contains:

```toml
[package]
version = "0.1.7"
```
