### ISSUE TITLE
Add Capability to Disable Default Features on Nightly Builds

### ISSUE THREAD

**Issue by indiv0** [huonw/travis-cargo#53]
Currently, in my `.travis.yml` I have something like the following:

``` yml
...

script:
  - |
      if [[ "$TRAVIS_RUST_VERSION" == nightly* ]]; then
        travis-cargo build -- --no-default-features
      else
        travis-cargo build
      fi

...

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE="nightly-testing"

...
```

Would it be possible to add some kind of flag to travis-cargo to disable all default features if built on nightly, so that I could have something like this instead:

``` yml
...

script:
  - |
      travis-cargo build

...

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE="nightly-testing"
    - TRAVIS_CARGO_DISABLE_DEFAULT_FEATURES_ON_NIGHTLY="true"

...
```
