### ISSUE TITLE
doc-upload for proc-macro crates

### ISSUE THREAD

**Issue by colin-kiegel** [huonw/travis-cargo#69]
`Cargo.toml`
```toml
# ... the usual
[lib]
proc-macro = true
```

Then `travis-cargo doc-upload` will fail:
```
error: uploading docs for package with no library
```

https://github.com/huonw/travis-cargo/blob/af51893dda0a1e20ece7f9c5b73c2805eb7b9059/travis_cargo.py#L129-L131

**Comment by colin-kiegel** [comment]
PS: I tried a workaround in `Cargo.toml`, but that does NOT work (same error as above):
```toml
[lib]
proc-macro = true
name = "foo" # <-- does not help.. :-(
```
