### ISSUE TITLE
kcov without root

### ISSUE THREAD

**Issue by jonas-schievink** [huonw/travis-cargo#7]
`libelf-dev` is now on the apt-get whitelist, so kcov can be built using the container-based infrastructure (see travis-ci/travis-ci#3680).

The `.travis.yml` of projects using this would have to include this:
```yml
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
```
